/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author migue
 */
public class GuiAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GuiAdmin
     */
    public GuiAdmin() {
        initComponents();
        setTitle("Administrador");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMostrarClientes = new javax.swing.JButton();
        btnMostrarMensajeros = new javax.swing.JButton();
        btnMostrarServicios = new javax.swing.JButton();
        btnMostrarPagos = new javax.swing.JButton();
        btnPagosMensajero = new javax.swing.JButton();
        btnTarifa = new javax.swing.JButton();
        btnCiudad = new javax.swing.JButton();
        btnCalificacion = new javax.swing.JButton();
        btncambioestado = new javax.swing.JButton();
        btnHorarioMensajeros = new javax.swing.JButton();
        btnIndicaciones = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnGenerarPago = new javax.swing.JButton();

        btnActualizar5.setBackground(new java.awt.Color(0, 177, 255));
        btnActualizar5.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar5.setText("Mostrar Pagos Mensajero");
        btnActualizar5.setBorderPainted(false);
        btnActualizar5.setFocusPainted(false);
        btnActualizar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LetrasMcQueen.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rayopeque.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMostrarClientes.setBackground(new java.awt.Color(255, 0, 51));
        btnMostrarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarClientes.setText("MostrarClientes");
        btnMostrarClientes.setBorderPainted(false);
        btnMostrarClientes.setFocusPainted(false);
        btnMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClientesActionPerformed(evt);
            }
        });

        btnMostrarMensajeros.setBackground(new java.awt.Color(255, 0, 51));
        btnMostrarMensajeros.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarMensajeros.setText("MostrarMensajeros");
        btnMostrarMensajeros.setBorderPainted(false);
        btnMostrarMensajeros.setFocusPainted(false);
        btnMostrarMensajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMensajerosActionPerformed(evt);
            }
        });

        btnMostrarServicios.setBackground(new java.awt.Color(255, 0, 51));
        btnMostrarServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarServicios.setText("Mostrar Servicios");
        btnMostrarServicios.setBorderPainted(false);
        btnMostrarServicios.setFocusPainted(false);
        btnMostrarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarServiciosActionPerformed(evt);
            }
        });

        btnMostrarPagos.setBackground(new java.awt.Color(255, 0, 51));
        btnMostrarPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPagos.setText("Mostrar Pagos");
        btnMostrarPagos.setBorderPainted(false);
        btnMostrarPagos.setFocusPainted(false);
        btnMostrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPagosActionPerformed(evt);
            }
        });

        btnPagosMensajero.setBackground(new java.awt.Color(255, 0, 51));
        btnPagosMensajero.setForeground(new java.awt.Color(255, 255, 255));
        btnPagosMensajero.setText("Mostrar Pagos Mensajero");
        btnPagosMensajero.setBorderPainted(false);
        btnPagosMensajero.setFocusPainted(false);
        btnPagosMensajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosMensajeroActionPerformed(evt);
            }
        });

        btnTarifa.setBackground(new java.awt.Color(255, 0, 51));
        btnTarifa.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifa.setText("Tarifa");
        btnTarifa.setBorderPainted(false);
        btnTarifa.setFocusPainted(false);
        btnTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarifaActionPerformed(evt);
            }
        });

        btnCiudad.setBackground(new java.awt.Color(255, 0, 51));
        btnCiudad.setForeground(new java.awt.Color(255, 255, 255));
        btnCiudad.setText("Ciudad");
        btnCiudad.setBorderPainted(false);
        btnCiudad.setFocusPainted(false);
        btnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadActionPerformed(evt);
            }
        });

        btnCalificacion.setBackground(new java.awt.Color(255, 0, 51));
        btnCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificacion.setText("Calificacion");
        btnCalificacion.setBorderPainted(false);
        btnCalificacion.setFocusPainted(false);
        btnCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionActionPerformed(evt);
            }
        });

        btncambioestado.setBackground(new java.awt.Color(255, 0, 51));
        btncambioestado.setForeground(new java.awt.Color(255, 255, 255));
        btncambioestado.setText("Procesos");
        btncambioestado.setBorderPainted(false);
        btncambioestado.setFocusPainted(false);
        btncambioestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambioestadoActionPerformed(evt);
            }
        });

        btnHorarioMensajeros.setBackground(new java.awt.Color(255, 0, 51));
        btnHorarioMensajeros.setForeground(new java.awt.Color(255, 255, 255));
        btnHorarioMensajeros.setText("Horario Mensajeros");
        btnHorarioMensajeros.setBorderPainted(false);
        btnHorarioMensajeros.setFocusPainted(false);
        btnHorarioMensajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioMensajerosActionPerformed(evt);
            }
        });

        btnIndicaciones.setBackground(new java.awt.Color(255, 0, 51));
        btnIndicaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnIndicaciones.setText("Indicaciones");
        btnIndicaciones.setBorderPainted(false);
        btnIndicaciones.setFocusPainted(false);
        btnIndicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndicacionesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMIN");

        btnGenerarPago.setBackground(new java.awt.Color(255, 0, 51));
        btnGenerarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarPago.setText("Generar Pagos");
        btnGenerarPago.setBorderPainted(false);
        btnGenerarPago.setFocusPainted(false);
        btnGenerarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMostrarPagos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarMensajeros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnMostrarClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnHorarioMensajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncambioestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addComponent(btnCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagosMensajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIndicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarClientes)
                    .addComponent(btnHorarioMensajeros)
                    .addComponent(btnPagosMensajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarMensajeros)
                    .addComponent(btncambioestado)
                    .addComponent(btnIndicaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarServicios)
                    .addComponent(btnCalificacion)
                    .addComponent(btnTarifa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarPagos)
                    .addComponent(btnCiudad)
                    .addComponent(btnGenerarPago))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarClientesActionPerformed

    private void btnMostrarMensajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMensajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarMensajerosActionPerformed

    private void btnMostrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarServiciosActionPerformed

    private void btnMostrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPagosActionPerformed

    private void btnPagosMensajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosMensajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagosMensajeroActionPerformed

    private void btnActualizar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar5ActionPerformed

    private void btnTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarifaActionPerformed

    private void btnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCiudadActionPerformed

    private void btnCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalificacionActionPerformed

    private void btncambioestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambioestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncambioestadoActionPerformed

    private void btnHorarioMensajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioMensajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorarioMensajerosActionPerformed

    private void btnIndicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndicacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIndicacionesActionPerformed

    private void btnGenerarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarPagoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar5;
    public javax.swing.JButton btnCalificacion;
    public javax.swing.JButton btnCiudad;
    public javax.swing.JButton btnGenerarPago;
    public javax.swing.JButton btnHorarioMensajeros;
    public javax.swing.JButton btnIndicaciones;
    public javax.swing.JButton btnMostrarClientes;
    public javax.swing.JButton btnMostrarMensajeros;
    public javax.swing.JButton btnMostrarPagos;
    public javax.swing.JButton btnMostrarServicios;
    public javax.swing.JButton btnPagosMensajero;
    public javax.swing.JButton btnTarifa;
    public javax.swing.JButton btncambioestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
