/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author migue
 */
public class GuiMensajero extends javax.swing.JFrame {

    /**
     * Creates new form GuiMesajero
     */
    public GuiMensajero() {
        initComponents();
        setTitle("Menu para Mensajero");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize  = getSize();
        setLocation((screenSize.width  - frameSize.width)  / 2, 
                    (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblServicioActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbServicio = new javax.swing.JTable();
        btnCambiarPerfil = new javax.swing.JButton();
        btnDetalleServicio = new javax.swing.JButton();
        txtIdMensajero = new javax.swing.JTextField();
        btnCalificacion = new javax.swing.JButton();
        btnBuscarServicio = new javax.swing.JButton();
        btnHistoricoServicios = new javax.swing.JButton();
        btnCobros = new javax.swing.JButton();
        txtBuscarServicioId = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JDateChooser();
        btnCerrarsesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesion Mensajero");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblServicioActual.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblServicioActual.setForeground(new java.awt.Color(255, 0, 51));
        lblServicioActual.setText("Id Mensajero");

        tbServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Servicio(id)", "Fecha Inicio", "Fecha Final", "Costo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tbServicio);

        btnCambiarPerfil.setBackground(new java.awt.Color(255, 0, 51));
        btnCambiarPerfil.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCambiarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarPerfil.setText("Actualizar Perfil");

        btnDetalleServicio.setBackground(new java.awt.Color(255, 0, 51));
        btnDetalleServicio.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnDetalleServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalleServicio.setText("Detalles del servicio");

        txtIdMensajero.setEditable(false);

        btnCalificacion.setBackground(new java.awt.Color(255, 0, 51));
        btnCalificacion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificacion.setText("Calificacion");

        btnBuscarServicio.setBackground(new java.awt.Color(255, 0, 51));
        btnBuscarServicio.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnBuscarServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarServicio.setText("Buscar servicio");

        btnHistoricoServicios.setBackground(new java.awt.Color(255, 0, 51));
        btnHistoricoServicios.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnHistoricoServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoricoServicios.setText("Historico");
        btnHistoricoServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoServiciosActionPerformed(evt);
            }
        });

        btnCobros.setBackground(new java.awt.Color(255, 0, 51));
        btnCobros.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCobros.setForeground(new java.awt.Color(255, 255, 255));
        btnCobros.setText("Cobros");

        Fecha.setDateFormatString("yyyy/MM/dd");

        btnCerrarsesion.setBackground(new java.awt.Color(255, 0, 51));
        btnCerrarsesion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarsesion.setText("Cerrar Sesion");

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Servicio");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LetrasMcQueen.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rayopeque.png"))); // NOI18N

        btnCobrar.setBackground(new java.awt.Color(255, 0, 51));
        btnCobrar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("Cobrar");
        btnCobrar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDetalleServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCambiarPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarsesion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(235, 235, 235))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(txtIdMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblServicioActual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHistoricoServicios)
                        .addGap(18, 18, 18)
                        .addComponent(btnCobros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarServicioId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarServicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServicioActual))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHistoricoServicios)
                        .addComponent(jLabel1)
                        .addComponent(btnCobros))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarServicio)
                        .addComponent(txtBuscarServicioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(Fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalleServicio)
                    .addComponent(btnCalificacion)
                    .addComponent(btnCobrar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarPerfil)
                    .addComponent(btnCerrarsesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoricoServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoServiciosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser Fecha;
    public javax.swing.JButton btnBuscarServicio;
    public javax.swing.JButton btnCalificacion;
    public javax.swing.JButton btnCambiarPerfil;
    public javax.swing.JButton btnCerrarsesion;
    public javax.swing.JButton btnCobrar;
    public javax.swing.JButton btnCobros;
    public javax.swing.JButton btnDetalleServicio;
    public javax.swing.JButton btnHistoricoServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblServicioActual;
    public javax.swing.JTable tbServicio;
    public javax.swing.JTextField txtBuscarServicioId;
    public javax.swing.JTextField txtIdMensajero;
    // End of variables declaration//GEN-END:variables
}
