/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author migue
 */
public class GuiServicio extends javax.swing.JFrame {

    /**
     * Creates new form GuiServicio
     */
    public GuiServicio() {
        initComponents();
        this.setTitle("Servicio");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize  = getSize();
        setLocation((screenSize.width  - frameSize.width)  / 2, 
                    (screenSize.height - frameSize.height) / 2);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdServicio = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblIdmensajero = new javax.swing.JLabel();
        lblCalificacion = new javax.swing.JLabel();
        btnCalificacion = new javax.swing.JButton();
        txtIdServicio = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        lblEstServ = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblFInicio = new javax.swing.JLabel();
        txtFInicio = new javax.swing.JTextField();
        txtFFinal = new javax.swing.JTextField();
        lblFFinal = new javax.swing.JLabel();
        txtEstadoServicio = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtIdMensajero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetalles = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        lblTDiligencia = new javax.swing.JLabel();
        txtTDiligencia = new javax.swing.JTextField();
        lblTRecorrido = new javax.swing.JLabel();
        txtTRecorrido = new javax.swing.JTextField();
        lblValorServ = new javax.swing.JLabel();
        txtValorServicio = new javax.swing.JTextField();
        lblMetPago = new javax.swing.JLabel();
        txtMetPago = new javax.swing.JTextField();
        btnCamEstServ = new javax.swing.JButton();
        cbxCambioestado = new javax.swing.JComboBox<>();
        btncambioestado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtcomentario = new javax.swing.JTextField();
        txtponerCalificacion = new javax.swing.JTextField();
        cbxPagar = new javax.swing.JComboBox<>();
        btnCalificarAceptar = new javax.swing.JButton();
        btnPagarAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblIdServicio.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblIdServicio.setForeground(new java.awt.Color(255, 0, 51));
        lblIdServicio.setText("IdServicio");

        lblIdCliente.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblIdCliente.setForeground(new java.awt.Color(255, 0, 51));
        lblIdCliente.setText("IdCliente");

        lblIdmensajero.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblIdmensajero.setForeground(new java.awt.Color(255, 0, 51));
        lblIdmensajero.setText("IdMensajero");

        lblCalificacion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(255, 0, 51));
        lblCalificacion.setText("Calificacion");

        btnCalificacion.setBackground(new java.awt.Color(255, 0, 51));
        btnCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificacion.setText("Calificacion");

        txtIdServicio.setEditable(false);
        txtIdServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdServicioActionPerformed(evt);
            }
        });

        txtCalificacion.setEditable(false);

        lblEstServ.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblEstServ.setForeground(new java.awt.Color(255, 0, 51));
        lblEstServ.setText("Estado del servicio");

        lblCiudad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(255, 0, 51));
        lblCiudad.setText("Ciudad");

        lblFInicio.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblFInicio.setForeground(new java.awt.Color(255, 0, 51));
        lblFInicio.setText("Fecha inicio");

        txtFInicio.setEditable(false);
        txtFInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFInicioActionPerformed(evt);
            }
        });

        txtFFinal.setEditable(false);

        lblFFinal.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblFFinal.setForeground(new java.awt.Color(255, 0, 51));
        lblFFinal.setText("Fecha Finalizacion");

        txtEstadoServicio.setEditable(false);
        txtEstadoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoServicioActionPerformed(evt);
            }
        });

        txtCiudad.setEditable(false);

        txtIdCliente.setEditable(false);
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtIdMensajero.setEditable(false);
        txtIdMensajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMensajeroActionPerformed(evt);
            }
        });

        tbDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdDireccion", "Direccion", "Detalle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDetalles);

        btnPagar.setBackground(new java.awt.Color(255, 0, 51));
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");

        lblTDiligencia.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblTDiligencia.setForeground(new java.awt.Color(255, 0, 51));
        lblTDiligencia.setText("Tipo de Diligencia");

        txtTDiligencia.setEditable(false);
        txtTDiligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTDiligenciaActionPerformed(evt);
            }
        });

        lblTRecorrido.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblTRecorrido.setForeground(new java.awt.Color(255, 0, 51));
        lblTRecorrido.setText("Tipo de Recorrido");

        txtTRecorrido.setEditable(false);

        lblValorServ.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblValorServ.setForeground(new java.awt.Color(255, 0, 51));
        lblValorServ.setText("Valor del servicio");

        txtValorServicio.setEditable(false);

        lblMetPago.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblMetPago.setForeground(new java.awt.Color(255, 0, 51));
        lblMetPago.setText("Metodo de pago");

        txtMetPago.setEditable(false);

        btnCamEstServ.setBackground(new java.awt.Color(255, 0, 51));
        btnCamEstServ.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnCamEstServ.setForeground(new java.awt.Color(255, 255, 255));
        btnCamEstServ.setText("Cambiar Estado Servicio");

        cbxCambioestado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cbxCambioestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cancelado", "Finalizar" }));
        cbxCambioestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCambioestadoActionPerformed(evt);
            }
        });

        btncambioestado.setBackground(new java.awt.Color(255, 0, 51));
        btncambioestado.setForeground(new java.awt.Color(255, 255, 255));
        btncambioestado.setText("Aceptar");

        btnVolver.setBackground(new java.awt.Color(255, 0, 51));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Cerrar Sesion");
        btnVolver.setFocusPainted(false);

        cbxPagar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cbxPagar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "PSE", "Efectivo" }));
        cbxPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPagarActionPerformed(evt);
            }
        });

        btnCalificarAceptar.setBackground(new java.awt.Color(255, 0, 51));
        btnCalificarAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificarAceptar.setText("Calificar");

        btnPagarAceptar.setBackground(new java.awt.Color(255, 0, 51));
        btnPagarAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagarAceptar.setText("Pagar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LetrasMcQueen.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rayopeque.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblValorServ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdServicio)
                                    .addComponent(lblIdCliente)
                                    .addComponent(lblIdmensajero)
                                    .addComponent(lblCiudad)
                                    .addComponent(lblCalificacion))
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdServicio)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdMensajero, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtValorServicio)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMetPago)
                        .addGap(18, 18, 18)
                        .addComponent(txtMetPago, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblTRecorrido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFFinal)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstServ)
                                        .addComponent(lblTDiligencia)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTDiligencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcomentario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnVolver)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnCalificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtponerCalificacion, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnCalificarAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbxPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPagarAceptar))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxCambioestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btncambioestado))
                                        .addComponent(btnCamEstServ)))))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdServicio)
                                    .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdCliente)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdmensajero)
                                    .addComponent(txtIdMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCiudad)
                                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTDiligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFInicio)
                        .addGap(18, 18, 18)
                        .addComponent(lblFFinal)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTDiligencia)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCalificacion)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorServ)
                            .addComponent(txtValorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTRecorrido))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetPago)
                    .addComponent(txtMetPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalificacion)
                    .addComponent(btnPagar)
                    .addComponent(cbxPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCamEstServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarAceptar)
                    .addComponent(cbxCambioestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncambioestado)
                    .addComponent(txtponerCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalificarAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdServicioActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtIdMensajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMensajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMensajeroActionPerformed

    private void txtEstadoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoServicioActionPerformed

    private void txtFInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFInicioActionPerformed

    private void txtTDiligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTDiligenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTDiligenciaActionPerformed

    private void cbxCambioestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCambioestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCambioestadoActionPerformed

    private void cbxPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPagarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalificacion;
    public javax.swing.JButton btnCalificarAceptar;
    public javax.swing.JButton btnCamEstServ;
    public javax.swing.JButton btnPagar;
    public javax.swing.JButton btnPagarAceptar;
    public javax.swing.JButton btnVolver;
    public javax.swing.JButton btncambioestado;
    public javax.swing.JComboBox<String> cbxCambioestado;
    public javax.swing.JComboBox<String> cbxPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblEstServ;
    private javax.swing.JLabel lblFFinal;
    private javax.swing.JLabel lblFInicio;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdServicio;
    private javax.swing.JLabel lblIdmensajero;
    private javax.swing.JLabel lblMetPago;
    private javax.swing.JLabel lblTDiligencia;
    private javax.swing.JLabel lblTRecorrido;
    private javax.swing.JLabel lblValorServ;
    public javax.swing.JTable tbDetalles;
    public javax.swing.JTextField txtCalificacion;
    public javax.swing.JTextField txtCiudad;
    public javax.swing.JTextField txtEstadoServicio;
    public javax.swing.JTextField txtFFinal;
    public javax.swing.JTextField txtFInicio;
    public javax.swing.JTextField txtIdCliente;
    public javax.swing.JTextField txtIdMensajero;
    public javax.swing.JTextField txtIdServicio;
    public javax.swing.JTextField txtMetPago;
    public javax.swing.JTextField txtTDiligencia;
    public javax.swing.JTextField txtTRecorrido;
    public javax.swing.JTextField txtValorServicio;
    public javax.swing.JTextField txtcomentario;
    public javax.swing.JTextField txtponerCalificacion;
    // End of variables declaration//GEN-END:variables
}
